package(default_visibility = ["//visibility:public"])

cc_library(
    name = "loggers",
    srcs = [
        "GlobalLogger.cpp",
        "GlobalLogger.h",
    ],
    hdrs = ["GlobalLogger.h"],
    include_prefix = "gams/loggers",
    deps = [
        "@gams//:gams_base",
        "@madara",
    ],
)
