# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xeab9aa1ec48eb0d0;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Polygon.capnp".Polygon;

# Type definition
struct Detection {
   confidence @0: Float32;
   polygon @1: Polygon;
   classification @2: UInt8;
   frameId @3: Text;
   source @4: Text;
   action @5: UInt8;
   id @6: UInt32;
   
}
