# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xd73f7bc93387b0a4;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;

# Type definition
struct Environment {
   environment @0: UInt8;
   header @1: Header;
   likelihoods @2: List(Float32);
   
}
