# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xe5ca7c09f827fc02;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "PointStamped.capnp".PointStamped;
using import "PolygonStamped.capnp".PolygonStamped;

# Type definition
struct ExploreGoal {
   exploreBoundary @0: PolygonStamped;
   returnPoint @1: PointStamped;
   
}
