# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xb33f12a37a48e3a7;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct GoalID {
   stamp @0: Int64;
   id @1: Text;
   
}
