# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xa919ca2162e43047;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "GoalID.capnp".GoalID;
using import "Header.capnp".Header;
using import "GotoGoal.capnp".GotoGoal;

# Type definition
struct GotoActionGoal {
   header @0: Header;
   goalId @1: GoalID;
   goal @2: GotoGoal;
   
}
