# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xe47e280738d2a6ea;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;

# Type definition
struct LctoMetric {
   overRanBuffer @0: Bool;
   timerCbPeriod @1: Float64;
   lctoCollision @2: Bool;
   bufferLength @3: Int32;
   wpIndex @4: Int32;
   triggerShortGlobalPath @5: Bool;
   unsafeLocalPath @6: Bool;
   triggerInvalidTfs @7: Bool;
   triggerRealignMode @8: Bool;
   triggerYawExceedance @9: Bool;
   wasPathPadded @10: Bool;
   triggerUnsafeLocalPath @11: Bool;
   currentTime @12: Float64;
   kAccel @13: Float64;
   reinitBp @14: Bool;
   header @15: Header;
   longLocalPath @16: Bool;
   bpVy0 @17: Float64;
   triggerHoverMode @18: Bool;
   lctoAccelFail @19: Bool;
   globalPlanSequence @20: Int32;
   lctoSuccess @21: Bool;
   bufferStartIndex @22: Int32;
   kVel @23: Float64;
   bpAx0 @24: Float64;
   triggerVelExceedance @25: Bool;
   bpAy0 @26: Float64;
   stopMovingAlongTraj @27: Bool;
   lctoSolveTime @28: Float64;
   nanBoundaryCondition @29: Bool;
   triggerInvalidMsg @30: Bool;
   bpVx0 @31: Float64;
   tMidpointAccel @32: Float64;
   tMidpointVel @33: Float64;
   triggerPosExceedance @34: Bool;
   
}
