# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xa27fc969bd8ae647;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct Net {
   interface @0: Text;
   read @1: Float32;
   write @2: Float32;
   
}
