# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xd3600d8e41aac5dd;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;
using import "Polygon.capnp".Polygon;

# Type definition
struct PolygonStamped {
   header @0: Header;
   polygon @1: Polygon;
   
}
