// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: PoseWithCovariance.capn

#include "PoseWithCovariance.capn.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<55> b_fcb83f4fad5bc6a0 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    160, 198,  91, 173,  79,  63, 184, 252,
     24,   0,   0,   0,   1,   0,   0,   0,
    189, 243, 255, 230,  84, 221, 148, 131,
      2,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  90,   1,   0,   0,
     41,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     80, 111, 115, 101,  87, 105, 116, 104,
     67, 111, 118,  97, 114, 105,  97, 110,
     99, 101,  46,  99,  97, 112, 110,  58,
     80, 111, 115, 101,  87, 105, 116, 104,
     67, 111, 118,  97, 114, 105,  97, 110,
     99, 101,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     45,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     44,   0,   0,   0,   3,   0,   1,   0,
     72,   0,   0,   0,   2,   0,   1,   0,
    112, 111, 115, 101,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    127, 240,  77, 233, 213, 173, 217, 231,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99, 111, 118,  97, 114, 105,  97, 110,
     99, 101,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   3,   0,   1,   0,
     10,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_fcb83f4fad5bc6a0 = b_fcb83f4fad5bc6a0.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_fcb83f4fad5bc6a0[] = {
  &s_e7d9add5e94df07f,
};
static const uint16_t m_fcb83f4fad5bc6a0[] = {1, 0};
static const uint16_t i_fcb83f4fad5bc6a0[] = {0, 1};
const ::capnp::_::RawSchema s_fcb83f4fad5bc6a0 = {
  0xfcb83f4fad5bc6a0, b_fcb83f4fad5bc6a0.words, 55, d_fcb83f4fad5bc6a0, m_fcb83f4fad5bc6a0,
  1, 2, i_fcb83f4fad5bc6a0, nullptr, nullptr, { &s_fcb83f4fad5bc6a0, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// PoseWithCovariance
constexpr uint16_t PoseWithCovariance::_capnpPrivate::dataWordSize;
constexpr uint16_t PoseWithCovariance::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind PoseWithCovariance::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* PoseWithCovariance::_capnpPrivate::schema;
#endif  // !CAPNP_LITE



