# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xa607bf6e460af911;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "PositionTarget.capnp".PositionTarget;

# Type definition
struct PositionTargetList {
   wps @0: List(PositionTarget);
   
}
