# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0x968ae29b7db1ace2;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;

# Type definition
struct State {
   header @0: Header;
   guided @1: Bool;
   connected @2: Bool;
   mode @3: Text;
   armed @4: Bool;
   
}
