# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xd0017397ccdb1fe1;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Net.capnp".Net;
using import "Process.capnp".Process;
using import "Cpu.capnp".Cpu;
using import "Wifi.capnp".Wifi;
using import "Disk.capnp".Disk;

# Type definition
struct SysStats {
   totalCpu @0: Float32;
   totalSwap @1: Float32;
   wifi @2: List(Wifi);
   process @3: List(Process);
   disks @4: List(Disk);
   totalMem @5: Float32;
   interface @6: List(Net);
   cpu @7: List(Cpu);
   
}
