# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xee9b14190947a136;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;

# Type definition
struct TerrainBounds {
   header @0: Header;
   terrainMax @1: Float64;
   terrainMin @2: Float64;
   
}
