# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xc9cd4094b0fef6e8;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;

# Type definition
struct TerrainHeight {
   header @0: Header;
   terrainHeight @1: Float64;
   
}
