// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: TwistWithCovariance.capn

#include "TwistWithCovariance.capn.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<55> b_bbe571f7f8647ce3 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    227, 124, 100, 248, 247, 113, 229, 187,
     25,   0,   0,   0,   1,   0,   0,   0,
    170, 144, 150, 132, 183,  34, 207, 131,
      2,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 106,   1,   0,   0,
     41,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     84, 119, 105, 115, 116,  87, 105, 116,
    104,  67, 111, 118,  97, 114, 105,  97,
    110,  99, 101,  46,  99,  97, 112, 110,
     58,  84, 119, 105, 115, 116,  87, 105,
    116, 104,  67, 111, 118,  97, 114, 105,
     97, 110,  99, 101,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     45,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     44,   0,   0,   0,   3,   0,   1,   0,
     72,   0,   0,   0,   2,   0,   1,   0,
    116, 119, 105, 115, 116,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    246,  18, 225,  17, 250,  46, 212, 163,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99, 111, 118,  97, 114, 105,  97, 110,
     99, 101,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   3,   0,   1,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_bbe571f7f8647ce3 = b_bbe571f7f8647ce3.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_bbe571f7f8647ce3[] = {
  &s_a3d42efa11e112f6,
};
static const uint16_t m_bbe571f7f8647ce3[] = {1, 0};
static const uint16_t i_bbe571f7f8647ce3[] = {0, 1};
const ::capnp::_::RawSchema s_bbe571f7f8647ce3 = {
  0xbbe571f7f8647ce3, b_bbe571f7f8647ce3.words, 55, d_bbe571f7f8647ce3, m_bbe571f7f8647ce3,
  1, 2, i_bbe571f7f8647ce3, nullptr, nullptr, { &s_bbe571f7f8647ce3, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// TwistWithCovariance
constexpr uint16_t TwistWithCovariance::_capnpPrivate::dataWordSize;
constexpr uint16_t TwistWithCovariance::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind TwistWithCovariance::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* TwistWithCovariance::_capnpPrivate::schema;
#endif  // !CAPNP_LITE



