# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xe7e90725df091fa0;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;

# Type definition
struct UpdateResiduals {
   header @0: Header;
   numFeatures @1: List(Int32);
   gammas @2: List(Float64);
   ids @3: List(Int32);
   res @4: List(Float64);
   
}
