# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0x80252b1220510fc9;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "PoseStamped.capnp".PoseStamped;

# Type definition
struct WallFollowGoal {
   wallFollowInitialPose @0: PoseStamped;
   
}
