/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GamsExport.h"
/* Header for class ai_gams_utility_Logging */

#ifndef _Included_ai_gams_utility_Logging
#define _Included_ai_gams_utility_Logging
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_gams_utility_Logging
 * Method:    jni_set_level
 * Signature: (I)V
 */
GAMS_EXPORT void JNICALL Java_ai_gams_utility_Logging_jni_1set_1level
  (JNIEnv *, jclass, jint);

/*
 * Class:     ai_gams_utility_Logging
 * Method:    jni_get_level
 * Signature: ()I
 */
GAMS_EXPORT jint JNICALL Java_ai_gams_utility_Logging_jni_1get_1level
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
