/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GamsExport.h"
/* Header for class ai_gams_variables_Self */

#ifndef _Included_ai_gams_variables_Self
#define _Included_ai_gams_variables_Self
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_gams_variables_Self
 * Method:    jni_Self
 * Signature: ()J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Self_jni_1Self__
  (JNIEnv *, jobject);

/*
 * Class:     ai_gams_variables_Self
 * Method:    jni_Self
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Self_jni_1Self__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Self
 * Method:    jni_freeSelf
 * Signature: (J)V
 */
GAMS_EXPORT void JNICALL Java_ai_gams_variables_Self_jni_1freeSelf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_gams_variables_Self
 * Method:    jni_init
 * Signature: (JJJLjava/lang/String;)V
 */
GAMS_EXPORT void JNICALL Java_ai_gams_variables_Self_jni_1init
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     ai_gams_variables_Self
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
GAMS_EXPORT jstring JNICALL Java_ai_gams_variables_Self_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Self
 * Method:    jni_getId
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Self_jni_1getId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Self
 * Method:    jni_getAgent
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Self_jni_1getAgent
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
