/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GamsExport.h"
/* Header for class ai_gams_variables_Agent */

#ifndef _Included_ai_gams_variables_Agent
#define _Included_ai_gams_variables_Agent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_Agent
 * Signature: ()J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1Agent__
  (JNIEnv *, jobject);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_Agent
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1Agent__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_freeAgent
 * Signature: (J)V
 */
GAMS_EXPORT void JNICALL Java_ai_gams_variables_Agent_jni_1freeAgent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_init
 * Signature: (JJJLjava/lang/String;)V
 */
GAMS_EXPORT void JNICALL Java_ai_gams_variables_Agent_jni_1init
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
GAMS_EXPORT jstring JNICALL Java_ai_gams_variables_Agent_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getBatteryRemaining
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getBatteryRemaining
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getBridgeId
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getBridgeId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getCommand
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getAlgorithm
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getArgs
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getAlgorithmArgs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getCoverageType
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getCoverageType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getDest
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getDest
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getHome
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getHome
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getIsMobile
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getIsMobile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getLocation
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getLocation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getMinAlt
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getMinAlt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getNextCoverageType
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getNextCoverageType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getSearchAreaId
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getSearchAreaId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getSource
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_gams_variables_Agent
 * Method:    jni_getTemperature
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_ai_gams_variables_Agent_jni_1getTemperature
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
