/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GamsExport.h"
/* Header for class com_gams_utility_GpsPosition */

#ifndef _Included_com_gams_utility_GpsPosition
#define _Included_com_gams_utility_GpsPosition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_GpsPosition
 * Signature: ()J
 */
GAMS_EXPORT jlong JNICALL Java_com_gams_utility_GpsPosition_jni_1GpsPosition__
  (JNIEnv *, jobject);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_GpsPosition
 * Signature: (J)J
 */
GAMS_EXPORT jlong JNICALL Java_com_gams_utility_GpsPosition_jni_1GpsPosition__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_GpsPosition
 * Signature: (DDD)J
 */
GAMS_EXPORT jlong JNICALL Java_com_gams_utility_GpsPosition_jni_1GpsPosition__DDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_freeGpsPosition
 * Signature: (J)V
 */
GAMS_EXPORT void JNICALL Java_com_gams_utility_GpsPosition_jni_1freeGpsPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
GAMS_EXPORT jstring JNICALL Java_com_gams_utility_GpsPosition_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_getLatitude
 * Signature: (J)D
 */
GAMS_EXPORT jdouble JNICALL Java_com_gams_utility_GpsPosition_jni_1getLatitude
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_getLongitude
 * Signature: (J)D
 */
GAMS_EXPORT jdouble JNICALL Java_com_gams_utility_GpsPosition_jni_1getLongitude
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_getAltitude
 * Signature: (J)D
 */
GAMS_EXPORT jdouble JNICALL Java_com_gams_utility_GpsPosition_jni_1getAltitude
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_setLatitude
 * Signature: (JD)V
 */
GAMS_EXPORT void JNICALL Java_com_gams_utility_GpsPosition_jni_1setLatitude
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_setLongitude
 * Signature: (JD)V
 */
GAMS_EXPORT void JNICALL Java_com_gams_utility_GpsPosition_jni_1setLongitude
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_gams_utility_GpsPosition
 * Method:    jni_setAltitude
 * Signature: (JD)V
 */
GAMS_EXPORT void JNICALL Java_com_gams_utility_GpsPosition_jni_1setAltitude
  (JNIEnv *, jobject, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
