/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GAMSExport.h"
/* Header for class com_gams_platforms_BasePlatform */

#ifndef _Included_com_gams_platforms_BasePlatform
#define _Included_com_gams_platforms_BasePlatform
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_gams_platforms_BasePlatform
 * Method:    jni_getKnowledgeBase
 * Signature: (J)J
 */
GAMSExport jlong JNICALL Java_com_gams_platforms_BasePlatform_jni_1getKnowledgeBase
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_platforms_BasePlatform
 * Method:    jni_getSelf
 * Signature: (J)J
 */
GAMSExport jlong JNICALL Java_com_gams_platforms_BasePlatform_jni_1getSelf
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_platforms_BasePlatform
 * Method:    jni_getPlatformStatus
 * Signature: (J)J
 */
GAMSExport jlong JNICALL Java_com_gams_platforms_BasePlatform_jni_1getPlatformStatus
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
