/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GAMS_Export.h"
/* Header for class com_gams_variables_Accent */

#ifndef _Included_com_gams_variables_Accent
#define _Included_com_gams_variables_Accent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_variables_Accent
 * Method:    jni_Accent
 * Signature: ()J
 */
GAMS_Export jlong JNICALL Java_com_gams_variables_Accent_jni_1Accent__
  (JNIEnv *, jobject);

/*
 * Class:     com_gams_variables_Accent
 * Method:    jni_Accent
 * Signature: (J)J
 */
GAMS_Export jlong JNICALL Java_com_gams_variables_Accent_jni_1Accent__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Accent
 * Method:    jni_freeAccent
 * Signature: (J)V
 */
GAMS_Export void JNICALL Java_com_gams_variables_Accent_jni_1freeAccent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gams_variables_Accent
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
GAMS_Export jstring JNICALL Java_com_gams_variables_Accent_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Accent
 * Method:    jni_init
 * Signature: (JJJLjava/lang/String;)V
 */
GAMS_Export void JNICALL Java_com_gams_variables_Accent_jni_1init
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_gams_variables_Accent
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
GAMS_Export jstring JNICALL Java_com_gams_variables_Accent_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Accent
 * Method:    jni_getArgs
 * Signature: (J)J
 */
GAMS_Export jlong JNICALL Java_com_gams_variables_Accent_jni_1getArgs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Accent
 * Method:    jni_getCommand
 * Signature: (J)J
 */
GAMS_Export jlong JNICALL Java_com_gams_variables_Accent_jni_1getCommand
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
