/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GAMS_Export.h"
/* Header for class com_gams_variables_Self */

#ifndef _Included_com_gams_variables_Self
#define _Included_com_gams_variables_Self
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_variables_Self
 * Method:    jni_Self
 * Signature: ()J
 */
GAMS_Export jlong JNICALL Java_com_gams_variables_Self_jni_1Self__
  (JNIEnv *, jobject);

/*
 * Class:     com_gams_variables_Self
 * Method:    jni_Self
 * Signature: (J)J
 */
GAMS_Export jlong JNICALL Java_com_gams_variables_Self_jni_1Self__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Self
 * Method:    jni_freeSelf
 * Signature: (J)V
 */
GAMS_Export void JNICALL Java_com_gams_variables_Self_jni_1freeSelf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gams_variables_Self
 * Method:    jni_init
 * Signature: (JJJLjava/lang/String;)V
 */
GAMS_Export void JNICALL Java_com_gams_variables_Self_jni_1init
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_gams_variables_Self
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
GAMS_Export jstring JNICALL Java_com_gams_variables_Self_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Self
 * Method:    jni_getId
 * Signature: (J)J
 */
GAMS_Export jlong JNICALL Java_com_gams_variables_Self_jni_1getId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Self
 * Method:    jni_getDevice
 * Signature: (J)J
 */
GAMS_Export jlong JNICALL Java_com_gams_variables_Self_jni_1getDevice
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
