/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GAMS_Export.h"
/* Header for class com_gams_logger_GlobalLogger */

#ifndef _Included_com_gams_logger_GlobalLogger
#define _Included_com_gams_logger_GlobalLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_getCPtr
 * Signature: ()J
 */
GAMS_Export jlong JNICALL Java_com_gams_logger_GlobalLogger_jni_1getCPtr
  (JNIEnv *, jclass);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_setLevel
 * Signature: (I)V
 */
GAMS_Export void JNICALL Java_com_gams_logger_GlobalLogger_jni_1setLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_getLevel
 * Signature: ()I
 */
GAMS_Export jint JNICALL Java_com_gams_logger_GlobalLogger_jni_1getLevel
  (JNIEnv *, jclass);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_getTag
 * Signature: ()Ljava/lang/String;
 */
GAMS_Export jstring JNICALL Java_com_gams_logger_GlobalLogger_jni_1getTag
  (JNIEnv *, jclass);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_setTag
 * Signature: (Ljava/lang/String;)V
 */
GAMS_Export void JNICALL Java_com_gams_logger_GlobalLogger_jni_1setTag
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_addTerm
 * Signature: ()V
 */
GAMS_Export void JNICALL Java_com_gams_logger_GlobalLogger_jni_1addTerm
  (JNIEnv *, jclass);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_addSyslog
 * Signature: ()V
 */
GAMS_Export void JNICALL Java_com_gams_logger_GlobalLogger_jni_1addSyslog
  (JNIEnv *, jclass);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_clear
 * Signature: ()V
 */
GAMS_Export void JNICALL Java_com_gams_logger_GlobalLogger_jni_1clear
  (JNIEnv *, jclass);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_addFile
 * Signature: (Ljava/lang/String;)V
 */
GAMS_Export void JNICALL Java_com_gams_logger_GlobalLogger_jni_1addFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gams_logger_GlobalLogger
 * Method:    jni_log
 * Signature: (ILjava/lang/String;)V
 */
GAMS_Export void JNICALL Java_com_gams_logger_GlobalLogger_jni_1log
  (JNIEnv *, jclass, jint, jstring);

/*
* Class:     com_gams_logger_GlobalLogger
* Method:    jni_setTimestampFormat
* Signature: (Ljava/lang/String;)V
*/
GAMS_Export void JNICALL Java_com_gams_logger_GlobalLogger_jni_1setTimestampFormat
(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
