# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xea2d7c9b643c9622;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;
using import "Accel.capnp".Accel;

# Type definition
struct AccelStamped {
   header @0: Header;
   accel @1: Accel;
   
}
