# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0x9232edcfc5b9282d;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Accel.capnp".Accel;

# Type definition
struct AccelWithCovariance {
   accel @0: Accel;
   covariance @1: List(Float64);
   
}
