# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xd154a3e5e84a482a;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "AccelWithCovariance.capnp".AccelWithCovariance;
using import "Header.capnp".Header;

# Type definition
struct AccelWithCovarianceStamped {
   header @0: Header;
   accel @1: AccelWithCovariance;
   
}
