# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xf1b64363951b07da;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct ColorRGBA {
   a @0: Float32;
   r @1: Float32;
   b @2: Float32;
   g @3: Float32;
   
}
