# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xa860a147c7d4258d;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct Float32 {
   data @0: Float32;
   
}
