# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xe8a3c28802a00c1f;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct Float64 {
   data @0: Float64;
   
}
