# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0x931280812160fd1a;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "OccupancyGrid.capnp".OccupancyGrid;

# Type definition
struct GetMapResult {
   map @0: OccupancyGrid;
   
}
