# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xed5e4f4a0781a479;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "MultiArrayLayout.capnp".MultiArrayLayout;

# Type definition
struct Int64MultiArray {
   data @0: List(Int64);
   layout @1: MultiArrayLayout;
   
}
