# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xf9f2a1ea46026cdb;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct Int8 {
   data @0: Int8;
   
}
