# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xba81c7549e318d31;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;

# Type definition
struct Joy {
   buttons @0: List(Int32);
   header @1: Header;
   axes @2: List(Float32);
   
}
