# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xc280cc6d070702ef;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "JoyFeedback.capnp".JoyFeedback;

# Type definition
struct JoyFeedbackArray {
   array @0: List(JoyFeedback);
   
}
