# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xe413b5d7b79e4f11;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "JoyFeedback.capnp".JoyFeedback;

# Type definition
struct JoyFeedbackArray {
   array @0: List(JoyFeedback);
   
}
