# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xf66bb0e5d7f3fae7;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct LaserEcho {
   echoes @0: List(Float32);
   
}
