# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0x8a1ad46390d76ec7;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "MultiArrayDimension.capnp".MultiArrayDimension;

# Type definition
struct MultiArrayLayout {
   dim @0: List(MultiArrayDimension);
   dataOffset @1: UInt32;
   
}
