# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xcb37fa5111f5172c;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct NavSatStatus {
   status @0: Int8;
   service @1: UInt16;
   
}
