# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xbd59acca2c3795ff;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Point32.capnp".Point32;

# Type definition
struct Polygon {
   points @0: List(Point32);
   
}
