# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xb7525aaa7d682d2b;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "PoseWithCovariance.capnp".PoseWithCovariance;
using import "Header.capnp".Header;

# Type definition
struct PoseWithCovarianceStamped {
   header @0: Header;
   pose @1: PoseWithCovariance;
   
}
