# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xcd07af5382cbeb2f;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;
using import "Pose.capnp".Pose;

# Type definition
struct PoseArray {
   header @0: Header;
   poses @1: List(Pose);
   
}
