# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xce90aba86b62c8a8;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Pose.capnp".Pose;

# Type definition
struct PoseWithCovariance {
   pose @0: Pose;
   covariance @1: List(Float64);
   
}
