# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xe1296547cb745866;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;
using import "Quaternion.capnp".Quaternion;

# Type definition
struct QuaternionStamped {
   header @0: Header;
   quaternion @1: Quaternion;
   
}
