# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0x9b18a5397369b0dd;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;

# Type definition
struct Range {
   maxRange @0: Float32;
   radiationType @1: UInt8;
   fieldOfView @2: Float32;
   minRange @3: Float32;
   header @4: Header;
   range @5: Float32;
   
}
