# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xe65cf5e0f3b69d45;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Quaternion.capnp".Quaternion;
using import "Vector3.capnp".Vector3;

# Type definition
struct Transform {
   translation @0: Vector3;
   rotation @1: Quaternion;
   
}
