# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xb6f0ce423dcac200;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Twist.capnp".Twist;
using import "Header.capnp".Header;

# Type definition
struct TwistStamped {
   twist @0: Twist;
   header @1: Header;
   
}
