# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xfb3295f329469431;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Header.capnp".Header;
using import "TwistWithCovariance.capnp".TwistWithCovariance;

# Type definition
struct TwistWithCovarianceStamped {
   twist @0: TwistWithCovariance;
   header @1: Header;
   
}
