# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0x8ff0d99f85651967;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Twist.capnp".Twist;

# Type definition
struct TwistWithCovariance {
   twist @0: Twist;
   covariance @1: List(Float64);
   
}
