# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xb0ba4adf9d9d6f64;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "MultiArrayLayout.capnp".MultiArrayLayout;

# Type definition
struct UInt64MultiArray {
   data @0: List(UInt64);
   layout @1: MultiArrayLayout;
   
}
