# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xf639b8ca27f6db42;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "MultiArrayLayout.capnp".MultiArrayLayout;

# Type definition
struct UInt16MultiArray {
   data @0: List(UInt16);
   layout @1: MultiArrayLayout;
   
}
