# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xb28ccc98fc9b76a8;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct UInt8 {
   data @0: UInt8;
   
}
