package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "programs",
    srcs = ["gams_controller.cpp"],
    deps = [
        "@gams//src/gams/controllers",
        "@gams//src/gams/loggers",
        "@madara",
    ],
)
