// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: MultiArrayLayout.capn

#ifndef CAPNP_INCLUDED_b1cae0dde140e306_
#define CAPNP_INCLUDED_b1cae0dde140e306_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 6001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "MultiArrayDimension.capn.h"

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(da982ee7f3fe21ea);

}  // namespace schemas
}  // namespace capnp

namespace gams {
namespace types {

struct MultiArrayLayout {
  MultiArrayLayout() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(da982ee7f3fe21ea, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class MultiArrayLayout::Reader {
public:
  typedef MultiArrayLayout Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasDim() const;
  inline  ::capnp::List< ::gams::types::MultiArrayDimension>::Reader getDim() const;

  inline  ::uint32_t getDataOffset() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MultiArrayLayout::Builder {
public:
  typedef MultiArrayLayout Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasDim();
  inline  ::capnp::List< ::gams::types::MultiArrayDimension>::Builder getDim();
  inline void setDim( ::capnp::List< ::gams::types::MultiArrayDimension>::Reader value);
  inline  ::capnp::List< ::gams::types::MultiArrayDimension>::Builder initDim(unsigned int size);
  inline void adoptDim(::capnp::Orphan< ::capnp::List< ::gams::types::MultiArrayDimension>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::gams::types::MultiArrayDimension>> disownDim();

  inline  ::uint32_t getDataOffset();
  inline void setDataOffset( ::uint32_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MultiArrayLayout::Pipeline {
public:
  typedef MultiArrayLayout Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool MultiArrayLayout::Reader::hasDim() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool MultiArrayLayout::Builder::hasDim() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::gams::types::MultiArrayDimension>::Reader MultiArrayLayout::Reader::getDim() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::MultiArrayDimension>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::gams::types::MultiArrayDimension>::Builder MultiArrayLayout::Builder::getDim() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::MultiArrayDimension>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void MultiArrayLayout::Builder::setDim( ::capnp::List< ::gams::types::MultiArrayDimension>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::MultiArrayDimension>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::gams::types::MultiArrayDimension>::Builder MultiArrayLayout::Builder::initDim(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::MultiArrayDimension>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void MultiArrayLayout::Builder::adoptDim(
    ::capnp::Orphan< ::capnp::List< ::gams::types::MultiArrayDimension>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::MultiArrayDimension>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::gams::types::MultiArrayDimension>> MultiArrayLayout::Builder::disownDim() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::MultiArrayDimension>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::uint32_t MultiArrayLayout::Reader::getDataOffset() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t MultiArrayLayout::Builder::getDataOffset() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void MultiArrayLayout::Builder::setDataOffset( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

}  // namespace
}  // namespace

#endif  // CAPNP_INCLUDED_b1cae0dde140e306_
