// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: MultiDOFJointState.capn

#ifndef CAPNP_INCLUDED_9c88efe0ac48354c_
#define CAPNP_INCLUDED_9c88efe0ac48354c_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 6001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "Header.capn.h"
#include "Transform.capn.h"
#include "Twist.capn.h"
#include "Wrench.capn.h"

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(a7edfce223c2e99c);

}  // namespace schemas
}  // namespace capnp

namespace gams {
namespace types {

struct MultiDOFJointState {
  MultiDOFJointState() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a7edfce223c2e99c, 0, 5)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class MultiDOFJointState::Reader {
public:
  typedef MultiDOFJointState Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasTwist() const;
  inline  ::capnp::List< ::gams::types::Twist>::Reader getTwist() const;

  inline bool hasHeader() const;
  inline  ::gams::types::Header::Reader getHeader() const;

  inline bool hasJointNames() const;
  inline  ::capnp::Text::Reader getJointNames() const;

  inline bool hasTransforms() const;
  inline  ::capnp::List< ::gams::types::Transform>::Reader getTransforms() const;

  inline bool hasWrench() const;
  inline  ::capnp::List< ::gams::types::Wrench>::Reader getWrench() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MultiDOFJointState::Builder {
public:
  typedef MultiDOFJointState Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasTwist();
  inline  ::capnp::List< ::gams::types::Twist>::Builder getTwist();
  inline void setTwist( ::capnp::List< ::gams::types::Twist>::Reader value);
  inline  ::capnp::List< ::gams::types::Twist>::Builder initTwist(unsigned int size);
  inline void adoptTwist(::capnp::Orphan< ::capnp::List< ::gams::types::Twist>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::gams::types::Twist>> disownTwist();

  inline bool hasHeader();
  inline  ::gams::types::Header::Builder getHeader();
  inline void setHeader( ::gams::types::Header::Reader value);
  inline  ::gams::types::Header::Builder initHeader();
  inline void adoptHeader(::capnp::Orphan< ::gams::types::Header>&& value);
  inline ::capnp::Orphan< ::gams::types::Header> disownHeader();

  inline bool hasJointNames();
  inline  ::capnp::Text::Builder getJointNames();
  inline void setJointNames( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initJointNames(unsigned int size);
  inline void adoptJointNames(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownJointNames();

  inline bool hasTransforms();
  inline  ::capnp::List< ::gams::types::Transform>::Builder getTransforms();
  inline void setTransforms( ::capnp::List< ::gams::types::Transform>::Reader value);
  inline  ::capnp::List< ::gams::types::Transform>::Builder initTransforms(unsigned int size);
  inline void adoptTransforms(::capnp::Orphan< ::capnp::List< ::gams::types::Transform>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::gams::types::Transform>> disownTransforms();

  inline bool hasWrench();
  inline  ::capnp::List< ::gams::types::Wrench>::Builder getWrench();
  inline void setWrench( ::capnp::List< ::gams::types::Wrench>::Reader value);
  inline  ::capnp::List< ::gams::types::Wrench>::Builder initWrench(unsigned int size);
  inline void adoptWrench(::capnp::Orphan< ::capnp::List< ::gams::types::Wrench>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::gams::types::Wrench>> disownWrench();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MultiDOFJointState::Pipeline {
public:
  typedef MultiDOFJointState Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::gams::types::Header::Pipeline getHeader();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool MultiDOFJointState::Reader::hasTwist() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool MultiDOFJointState::Builder::hasTwist() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::gams::types::Twist>::Reader MultiDOFJointState::Reader::getTwist() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Twist>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::gams::types::Twist>::Builder MultiDOFJointState::Builder::getTwist() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Twist>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void MultiDOFJointState::Builder::setTwist( ::capnp::List< ::gams::types::Twist>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Twist>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::gams::types::Twist>::Builder MultiDOFJointState::Builder::initTwist(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Twist>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void MultiDOFJointState::Builder::adoptTwist(
    ::capnp::Orphan< ::capnp::List< ::gams::types::Twist>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Twist>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::gams::types::Twist>> MultiDOFJointState::Builder::disownTwist() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Twist>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool MultiDOFJointState::Reader::hasHeader() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool MultiDOFJointState::Builder::hasHeader() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::gams::types::Header::Reader MultiDOFJointState::Reader::getHeader() const {
  return ::capnp::_::PointerHelpers< ::gams::types::Header>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::gams::types::Header::Builder MultiDOFJointState::Builder::getHeader() {
  return ::capnp::_::PointerHelpers< ::gams::types::Header>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::gams::types::Header::Pipeline MultiDOFJointState::Pipeline::getHeader() {
  return  ::gams::types::Header::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void MultiDOFJointState::Builder::setHeader( ::gams::types::Header::Reader value) {
  ::capnp::_::PointerHelpers< ::gams::types::Header>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::gams::types::Header::Builder MultiDOFJointState::Builder::initHeader() {
  return ::capnp::_::PointerHelpers< ::gams::types::Header>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void MultiDOFJointState::Builder::adoptHeader(
    ::capnp::Orphan< ::gams::types::Header>&& value) {
  ::capnp::_::PointerHelpers< ::gams::types::Header>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::gams::types::Header> MultiDOFJointState::Builder::disownHeader() {
  return ::capnp::_::PointerHelpers< ::gams::types::Header>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool MultiDOFJointState::Reader::hasJointNames() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool MultiDOFJointState::Builder::hasJointNames() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader MultiDOFJointState::Reader::getJointNames() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder MultiDOFJointState::Builder::getJointNames() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void MultiDOFJointState::Builder::setJointNames( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder MultiDOFJointState::Builder::initJointNames(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void MultiDOFJointState::Builder::adoptJointNames(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> MultiDOFJointState::Builder::disownJointNames() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool MultiDOFJointState::Reader::hasTransforms() const {
  return !_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline bool MultiDOFJointState::Builder::hasTransforms() {
  return !_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::gams::types::Transform>::Reader MultiDOFJointState::Reader::getTransforms() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Transform>>::get(_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::gams::types::Transform>::Builder MultiDOFJointState::Builder::getTransforms() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Transform>>::get(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline void MultiDOFJointState::Builder::setTransforms( ::capnp::List< ::gams::types::Transform>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Transform>>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::gams::types::Transform>::Builder MultiDOFJointState::Builder::initTransforms(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Transform>>::init(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), size);
}
inline void MultiDOFJointState::Builder::adoptTransforms(
    ::capnp::Orphan< ::capnp::List< ::gams::types::Transform>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Transform>>::adopt(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::gams::types::Transform>> MultiDOFJointState::Builder::disownTransforms() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Transform>>::disown(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}

inline bool MultiDOFJointState::Reader::hasWrench() const {
  return !_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline bool MultiDOFJointState::Builder::hasWrench() {
  return !_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::gams::types::Wrench>::Reader MultiDOFJointState::Reader::getWrench() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Wrench>>::get(_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::gams::types::Wrench>::Builder MultiDOFJointState::Builder::getWrench() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Wrench>>::get(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline void MultiDOFJointState::Builder::setWrench( ::capnp::List< ::gams::types::Wrench>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Wrench>>::set(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::gams::types::Wrench>::Builder MultiDOFJointState::Builder::initWrench(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Wrench>>::init(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), size);
}
inline void MultiDOFJointState::Builder::adoptWrench(
    ::capnp::Orphan< ::capnp::List< ::gams::types::Wrench>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Wrench>>::adopt(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::gams::types::Wrench>> MultiDOFJointState::Builder::disownWrench() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Wrench>>::disown(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}

}  // namespace
}  // namespace

#endif  // CAPNP_INCLUDED_9c88efe0ac48354c_
