// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: PointCloud.capn

#ifndef CAPNP_INCLUDED_da394b35451e9328_
#define CAPNP_INCLUDED_da394b35451e9328_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 6001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "ChannelFloat32.capn.h"
#include "Header.capn.h"
#include "Point32.capn.h"

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(b77e1e7a8d36dff0);

}  // namespace schemas
}  // namespace capnp

namespace gams {
namespace types {

struct PointCloud {
  PointCloud() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(b77e1e7a8d36dff0, 0, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class PointCloud::Reader {
public:
  typedef PointCloud Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasChannels() const;
  inline  ::capnp::List< ::gams::types::ChannelFloat32>::Reader getChannels() const;

  inline bool hasHeader() const;
  inline  ::gams::types::Header::Reader getHeader() const;

  inline bool hasPoints() const;
  inline  ::capnp::List< ::gams::types::Point32>::Reader getPoints() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class PointCloud::Builder {
public:
  typedef PointCloud Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasChannels();
  inline  ::capnp::List< ::gams::types::ChannelFloat32>::Builder getChannels();
  inline void setChannels( ::capnp::List< ::gams::types::ChannelFloat32>::Reader value);
  inline  ::capnp::List< ::gams::types::ChannelFloat32>::Builder initChannels(unsigned int size);
  inline void adoptChannels(::capnp::Orphan< ::capnp::List< ::gams::types::ChannelFloat32>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::gams::types::ChannelFloat32>> disownChannels();

  inline bool hasHeader();
  inline  ::gams::types::Header::Builder getHeader();
  inline void setHeader( ::gams::types::Header::Reader value);
  inline  ::gams::types::Header::Builder initHeader();
  inline void adoptHeader(::capnp::Orphan< ::gams::types::Header>&& value);
  inline ::capnp::Orphan< ::gams::types::Header> disownHeader();

  inline bool hasPoints();
  inline  ::capnp::List< ::gams::types::Point32>::Builder getPoints();
  inline void setPoints( ::capnp::List< ::gams::types::Point32>::Reader value);
  inline  ::capnp::List< ::gams::types::Point32>::Builder initPoints(unsigned int size);
  inline void adoptPoints(::capnp::Orphan< ::capnp::List< ::gams::types::Point32>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::gams::types::Point32>> disownPoints();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class PointCloud::Pipeline {
public:
  typedef PointCloud Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::gams::types::Header::Pipeline getHeader();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool PointCloud::Reader::hasChannels() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool PointCloud::Builder::hasChannels() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::gams::types::ChannelFloat32>::Reader PointCloud::Reader::getChannels() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::ChannelFloat32>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::gams::types::ChannelFloat32>::Builder PointCloud::Builder::getChannels() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::ChannelFloat32>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void PointCloud::Builder::setChannels( ::capnp::List< ::gams::types::ChannelFloat32>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::ChannelFloat32>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::gams::types::ChannelFloat32>::Builder PointCloud::Builder::initChannels(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::ChannelFloat32>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void PointCloud::Builder::adoptChannels(
    ::capnp::Orphan< ::capnp::List< ::gams::types::ChannelFloat32>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::ChannelFloat32>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::gams::types::ChannelFloat32>> PointCloud::Builder::disownChannels() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::ChannelFloat32>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool PointCloud::Reader::hasHeader() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool PointCloud::Builder::hasHeader() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::gams::types::Header::Reader PointCloud::Reader::getHeader() const {
  return ::capnp::_::PointerHelpers< ::gams::types::Header>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::gams::types::Header::Builder PointCloud::Builder::getHeader() {
  return ::capnp::_::PointerHelpers< ::gams::types::Header>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::gams::types::Header::Pipeline PointCloud::Pipeline::getHeader() {
  return  ::gams::types::Header::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void PointCloud::Builder::setHeader( ::gams::types::Header::Reader value) {
  ::capnp::_::PointerHelpers< ::gams::types::Header>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::gams::types::Header::Builder PointCloud::Builder::initHeader() {
  return ::capnp::_::PointerHelpers< ::gams::types::Header>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void PointCloud::Builder::adoptHeader(
    ::capnp::Orphan< ::gams::types::Header>&& value) {
  ::capnp::_::PointerHelpers< ::gams::types::Header>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::gams::types::Header> PointCloud::Builder::disownHeader() {
  return ::capnp::_::PointerHelpers< ::gams::types::Header>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool PointCloud::Reader::hasPoints() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool PointCloud::Builder::hasPoints() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::gams::types::Point32>::Reader PointCloud::Reader::getPoints() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Point32>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::gams::types::Point32>::Builder PointCloud::Builder::getPoints() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Point32>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void PointCloud::Builder::setPoints( ::capnp::List< ::gams::types::Point32>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Point32>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::gams::types::Point32>::Builder PointCloud::Builder::initPoints(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Point32>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void PointCloud::Builder::adoptPoints(
    ::capnp::Orphan< ::capnp::List< ::gams::types::Point32>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Point32>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::gams::types::Point32>> PointCloud::Builder::disownPoints() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::gams::types::Point32>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

}  // namespace
}  // namespace

#endif  // CAPNP_INCLUDED_da394b35451e9328_
